name: Hello World
on:
  push:
    branches:
      - dev
      - internal
      - master
      - release
  pull_request:
    branches:
      - dev
      - internal
      - master
      - release
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello, World"
